### ISSUE TITLE
Please make a new release on pypi :)

### ISSUE THREAD

**Issue by simahawk** [akretion/locomotivecms-python-client#5]
@sebastienbeau

**Comment by simahawk** [comment]
@sebastienbeau piiiiiiiiiiing!

**Comment by rousseldenis** [comment]
@sebastienbeau @sbidoul

**Comment by sbidoul** [comment]
Beyond hunting @sebastienbeau, there is not much I can do as I'm not a maintainer of the [PyPI project](https://pypi.org/project/locomotivecms/).

**Comment by simahawk** [comment]
@sebastienbeau pls pls pls :)

**Comment by simahawk** [comment]
we should have something like this indeed https://github.com/OCA/odoo-test-helper/blob/master/.github/workflows/ci.yml

**Comment by sbidoul** [comment]
@sebastienbeau if you give me (acsbidoul on PyPI) access to the PYPI project, I can do it.

**Comment by simahawk** [comment]
@sebastienbeau @sbidoul ping :)

**Comment by sbidoul** [comment]
Still happy to do the work as soon as I get access to the PyPI project.

**Comment by sbidoul** [comment]
Done :) Next releases can be done by creating a new GitHub releases.
